ebook_metadata:
  title: ༄༅། །སྐུ་གསུམ་ངོ་སྤྲོད་ཀྱི་རྣམ་པར་བཤད་པ་མདོ་རྒྱུད་བསྟན་པ་ཐ་དག་གི་ཨེ་ཝཾ་ཕྱག་རྒྱ།
    །
  authors:
  - མཛད་པ་པོ། ༧ཀརྨ་པ་མི་བསྐྱོད་རྡོ་རྗེ།
  sku: VVI-MD-003-2
  layers:
  - book_title
  - author
  - tsawa
  - quotation
  - sabche
  - yigchung
web_metadata:
  title:
    en: E-Wam Mahamudra That Embodies All Sutra and Tantra Teaching:An Introduction
      to the Three Kayas, Volume 2
    bo: སྐུ་གསུམ་ངོ་སྤྲོད་ཀྱི་རྣམ་པར་བཤད་པ་མདོ་རྒྱུད་བསྟན་པ་མཐའ་དག་གི་ཨེ་ཝཾ་ཕྱག་རྒྱ།
  collection:
    en: VVI Mikyo Dorje Series–  Book 3-2
    bo: མི་བསྐྱོད་རྡོ་རྗེ་གསུང་།–  དེབ། ༣-༢
  author:
    en: Eighth Karmapa Mikyo Dorje
    bo: ཀརྨ་པ་སྐུ་ཕྲེང་བརྒྱད་པ་མི་བསྐྱོད་རྡོ་རྗེ།
  pusblisher:
    en: Vajra Vidya Institute
    bo: བཛྲ་བིདྱཱ་གཙུག་ལག་སློབ་གཉེར་ཁང་།
  sku: VVI-MD-003-2
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: VVI-MD-003-2.epub
  description:
    en: ༄༅། །སྟོན་པ་དེའི་ཡུམ་ཤེས་རབ་མ་གང་གིས་འཁྱུད་པ་ན་བདེ་བ་ཆེན་པོ་དང་འབྲལ་མི་ཤེས་པར་ཐོབ་ནུས་པ་དེ་གང་ཞེ་ན།
      དེ་ནི་སྟོན་པ་རང་ཉིད་དང་གདོད་ནས་འབྲལ་མི་ཤེས་པར་བསྐྱེད་བྱེད་ཀྱི་ཡུམ་སྟོན་པ་རང་ཉིད་ཀྱི་བཞེད་དགུ་ཅོག་སྒྲུབ་པར་བྱེད་པའི་ཆོས་ཀྱི་རྒྱུ་དུས་གསུམ་དུ་བདེ་དགའི་དངོས་པོའི་ཚོགས་ཇི་ལྟར་དབྱུངས་ཀྱང་ཟད་མི་ཤེས་པ།
      གཙོ་བོའི་རིགས་ལས་རིགས་གཞན་དུ་མི་འགྲོ་བ། ཟུང་དུ་འཇུག་པས་རང་འོད་ཀྱི་རིག་མ་ཞེས་བྱ་བ་སྟེ་རིག་མ་འདི་དང་།
      རིགས་བདག་འདི་ཉིད་རྒྱུད་གཅིག་གམ་ཐ་དད་ཅེ་ན། ཆོས་དབྱིངས་རྣམ་པར་དག་པའི་རིགས་ཀྱི་དབང་དུ་བྱས་ན་འཁོར་འདས་ཀྱི་འགྲོ་བ་ཐམས་ཅད་ཀྱང་རྒྱུད་གཅིག་ཏུ་བསྡུ་ན།
      འདིའི་རྒྱུད་གཅིག་ཏུ་གྲུབ་པ་དང་མི་གྲུབ་པ་དོགས་པར་མི་བྱ་ལ། ཆོས་ཀྱི་དབྱིངས་ཟད་པ་མེད་པ་ལ་སྐུ་དང་ཡེ་ཤེས་ཟད་པ་མེད་པའི་རྟེན་དང་བརྟེན་པའི་དཀྱིལ་འཁོར་ཟད་པ་མེད་པའི་དབང་དུ་ན་རྒྱུད་ཐ་དད་པ་ལྟར་སྣང་ཡང་མི་འགལ་ཏེ།
      རང་ཉིད་ཀྱི་རིགས་ལས་འཕྲོས་པའི་རིགས་མཐའ་ཡས་པ་ཐམས་ཅད་ཀྱང་རིགས་དང་རྒྱུད་ཐ་དད་པར་སྤྲོ་ཞིང་།
      དེ་ལྟ་ནའང་རིགས་དང་རྒྱུད་ཐ་དད་པ་དེའང་རིགས་དང་རྒྱུད་གཅིག་གི་ཁོངས་སམ་ཕྱག་རྒྱ་ལས་འདའ་བ་མེད་པའི་ཕྱིར་རོ།
      །
    bo: ༄༅། །སྟོན་པ་དེའི་ཡུམ་ཤེས་རབ་མ་གང་གིས་འཁྱུད་པ་ན་བདེ་བ་ཆེན་པོ་དང་འབྲལ་མི་ཤེས་པར་ཐོབ་ནུས་པ་དེ་གང་ཞེ་ན།
      དེ་ནི་སྟོན་པ་རང་ཉིད་དང་གདོད་ནས་འབྲལ་མི་ཤེས་པར་བསྐྱེད་བྱེད་ཀྱི་ཡུམ་སྟོན་པ་རང་ཉིད་ཀྱི་བཞེད་དགུ་ཅོག་སྒྲུབ་པར་བྱེད་པའི་ཆོས་ཀྱི་རྒྱུ་དུས་གསུམ་དུ་བདེ་དགའི་དངོས་པོའི་ཚོགས་ཇི་ལྟར་དབྱུངས་ཀྱང་ཟད་མི་ཤེས་པ།
      གཙོ་བོའི་རིགས་ལས་རིགས་གཞན་དུ་མི་འགྲོ་བ། ཟུང་དུ་འཇུག་པས་རང་འོད་ཀྱི་རིག་མ་ཞེས་བྱ་བ་སྟེ་རིག་མ་འདི་དང་།
      རིགས་བདག་འདི་ཉིད་རྒྱུད་གཅིག་གམ་ཐ་དད་ཅེ་ན། ཆོས་དབྱིངས་རྣམ་པར་དག་པའི་རིགས་ཀྱི་དབང་དུ་བྱས་ན་འཁོར་འདས་ཀྱི་འགྲོ་བ་ཐམས་ཅད་ཀྱང་རྒྱུད་གཅིག་ཏུ་བསྡུ་ན།
      འདིའི་རྒྱུད་གཅིག་ཏུ་གྲུབ་པ་དང་མི་གྲུབ་པ་དོགས་པར་མི་བྱ་ལ། ཆོས་ཀྱི་དབྱིངས་ཟད་པ་མེད་པ་ལ་སྐུ་དང་ཡེ་ཤེས་ཟད་པ་མེད་པའི་རྟེན་དང་བརྟེན་པའི་དཀྱིལ་འཁོར་ཟད་པ་མེད་པའི་དབང་དུ་ན་རྒྱུད་ཐ་དད་པ་ལྟར་སྣང་ཡང་མི་འགལ་ཏེ།
      རང་ཉིད་ཀྱི་རིགས་ལས་འཕྲོས་པའི་རིགས་མཐའ་ཡས་པ་ཐམས་ཅད་ཀྱང་རིགས་དང་རྒྱུད་ཐ་དད་པར་སྤྲོ་ཞིང་།
      དེ་ལྟ་ནའང་རིགས་དང་རྒྱུད་ཐ་དད་པ་དེའང་རིགས་དང་རྒྱུད་གཅིག་གི་ཁོངས་སམ་ཕྱག་རྒྱ་ལས་འདའ་བ་མེད་པའི་ཕྱིར་རོ།
      །
